import test from 'node:test';
import assert from 'node:assert/strict';
import {extractSourceMetadata} from '../src/lib/public-page.ts';
const url='https://www.facebook.com/broker/posts/pfbidTEST',author='https://www.facebook.com/broker',canonical='https://www.facebook.com/broker/posts/test/12345/',text='Original public post text, not comments.';
function story(){const actor={id:'actor-id',url:author};return {__typename:'Story',id:'story-id',post_id:'12345',permalink_url:url,actors:[actor],comet_sections:{content:{story:{id:'story-id',post_id:'12345',wwwURL:url,actors:[{...actor}],message:{text},comet_sections:{message:{story:{id:'story-id',url,message:{text}}}}}}}};}
const parse=(roots,canon=canonical,extra='')=>extractSourceMetadata(`<link rel="canonical" href="${canon}">${extra}<script type="application/json">${JSON.stringify({data:{nodes:roots}})}</script><body>Log in</body>`,url);
test('public JSON binds exact story, text, numeric alias and author',()=>{const r=parse([story()]);assert.equal(r.bound_post.text,text);assert.equal(r.canonical_url,url);assert.deepEqual(r.bound_post.author_urls,[author]);});
test('identity, author and body disagreements fail closed',()=>{for(const mutate of [r=>r.id='different',r=>r.post_id='999',r=>r.actors=[],r=>r.actors.push({id:'other',url:author}),r=>r.actors[0].url='https://www.facebook.com/other',r=>r.comet_sections.content.story.actors[0].id='other',r=>r.comet_sections.content.story.comet_sections.message.story.url=url+'?comment_id=1',r=>r.comet_sections.content.story.message.text='comment',r=>r.comet_sections.content.story.wwwURL=url+'#comment',r=>r.comet_sections.content.story.message.text='x'.repeat(10001)]){const root=story();mutate(root);assert.equal(parse([root]).bound_post,undefined);}});
test('wrong publisher canonical, wrong numeric alias and reply URL reject',()=>{for(const c of ['https://www.facebook.com/other/posts/12345','https://www.facebook.com/broker/posts/999',canonical+'?reply_comment_id=1'])assert.equal(parse([story()],c).bound_post,undefined);});
test('comments cannot provide missing body or author',()=>{const r=story();r.__typename='Comment';assert.equal(parse([r]).bound_post,undefined);const missing=story();delete missing.comet_sections.content.story.message;missing.comment={text,author};assert.equal(parse([missing]).bound_post,undefined);});
test('duplicate exact stories must agree',()=>{assert.equal(parse([story(),story()]).bound_post.text,text);const other=story();other.comet_sections.content.story.message.text='Different';other.comet_sections.content.story.comet_sections.message.story.message.text='Different';assert.equal(parse([story(),other]).bound_post,undefined);});
test('JSON-LD conflicts cannot be hidden by numeric canonical aliases',()=>{const ld={'@type':'SocialMediaPosting',url,articleBody:'Conflicting original text',author:{url:author}};assert.equal(parse([story()],canonical,`<script type="application/ld+json">${JSON.stringify(ld)}</script>`).bound_post,undefined);});
test('script count, malformed JSON and depth budget fail closed',()=>{assert.equal(parse([story()],canonical,'<script type="application/json">{broken</script>').bound_post,undefined);assert.equal(parse([story()],canonical,'<script type="application/json">{}</script>'.repeat(65)).bound_post,undefined);let nested={};for(let i=0;i<60;i++)nested={nested};assert.equal(parse([story(),nested]).bound_post,undefined);});

test('JSON-LD body conflicts at the verified numeric canonical also reject',()=>{const ld={'@type':'SocialMediaPosting',url:canonical,articleBody:'Conflicting original text',author:{url:author}};assert.equal(parse([story()],canonical,`<script type="application/ld+json">${JSON.stringify(ld)}</script>`).bound_post,undefined);});

test('bare numeric alias JSON-LD conflict rejects too',()=>{const ld={'@type':'SocialMediaPosting',url:'https://www.facebook.com/broker/posts/12345',articleBody:'Conflicting',author:{url:author}};assert.equal(parse([story()],canonical,`<script type="application/ld+json">${JSON.stringify(ld)}</script>`).bound_post,undefined);});

test('path URLs carrying a conflicting query identity never bind',()=>{for(const query of ['story_fbid=OTHER','fbid=OTHER','id=OTHER']){const source=url+'?'+query;const root=story();root.permalink_url=source;root.comet_sections.content.story.wwwURL=source;root.comet_sections.content.story.comet_sections.message.story.url=source;const html=`<link rel="canonical" href="${source}"><script type="application/json">${JSON.stringify(root)}</script>`;assert.equal(extractSourceMetadata(html,source).bound_post,undefined);}});
