import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync(new URL('../src/lib/office-social-runner.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const setup={name:'Greater Impact Realty',discovery_location:'Jonesborough, Tennessee',agents:[{id:'j',name:'Jane Jones'},{id:'k',name:'Kevin Knoxville'}],discovery_agent_ids:['j']};
const card={library_id:'123456',source_url:'https://www.facebook.com/ads/library/?id=123456',observed_page_url:'https://www.facebook.com/ads/library/',captured_at:'2026-09-23T19:00:00Z',advertiser:{name:'Third Party',url:'https://www.facebook.com/thirdparty'},current_page_advertiser:null,attribution_note:'Publisher is not proof of brokerage ownership.',active:'active',started_running:'Sep 20, 2026',visible_text:'Active\nLibrary ID: 123456\nStarted running on Sep 20, 2026\nThird Party\nSponsored\nNew home in Jonesborough TN | Greater Impact Realty Jonesborough\nLearn more',truncated:false,media:[{kind:'video_poster',url:'https://cdn.example.com/poster.jpg',alt:'Poster'}],media_scope:'video_poster_only'};
function load(overrides={}){let collected=0;const exports={};vm.runInNewContext(source,{exports,Date,Error,Promise,require:name=>{
 if(name==='node:crypto')return {randomUUID:()=> 'run-id'};
 if(name==='./office-social-contract')return {OFFICE_SOCIAL_ID:'__office_public_social__'};
 if(name==='./meta-browser')return {collectMetaAds:async query=>{collected++;assert.equal(query,'Greater Impact Realty Jonesborough');return {status:'available',reason:'Sample',observed_page_url:'https://www.facebook.com/ads/library/',captured_at:card.captured_at,cards:[card],...overrides.found};}};
 if(name==='./public-image')return {readPublicImage:async()=>{if(overrides.imageFailure)throw Error('Unavailable');return {data_url:'data:image/jpeg;base64,YQ==',source_url:card.source_url,image_url:card.media[0].url,sha256:'a'.repeat(64),retrieved_at:card.captured_at};}};
 if(name==='./image-review')return {reviewAdImage:async()=>({status:'reviewed',observations:{creative_kind:'complete_ad',eho:'not_visible'},notes:'Image only'})};
 if(name==='./ad-review')return {reviewAdText:async()=>({result:'yellow',summary:'Partial source; verify.',flags:[]})};throw Error(name);
 }});return {...exports,collected:()=>collected};}
function database(prior=null){let saved;const query={eq(){return this},select(){return this},async single(){return {data:saved,error:null}}};return {rpc:async()=>({data:true}),from:()=>({select:()=>({eq(){return this},async maybeSingle(){return {data:prior,error:null}}}),update:value=>{saved=value;return query;}})};}
test('scope excludes other office names and unrelated brokerage matches',()=>{const m=load();assert.equal(m.socialRelevance({...card,visible_text:'Kevin Knoxville | Greater Impact Realty Knoxville'},setup),null);assert.equal(m.socialRelevance({...card,visible_text:'Other Firm Jonesborough'},setup),null);assert.equal(m.socialRelevance(card,setup).relevance,'office_reference');assert.equal(m.socialRelevance({...card,visible_text:'Jane Jones Greater Impact Realty listing in Knoxville'},setup).relevance,'roster_name_match');});
test('video poster evidence stays partial, saved bytes remain bound to ad and roster counts are untouched',async()=>{const m=load();const result=await m.runOfficeSocial(database(),'owner',setup);const ad=result.evidence.ads[0];assert.equal(ad.library_id,card.library_id);assert.equal(ad.image_review.capture.source_url,card.source_url);assert.equal(ad.image_data_url,'data:image/jpeg;base64,YQ==');assert.equal(ad.image_review.status,'partial');assert.match(ad.image_review.notes,/video poster/);assert.equal(ad.matched_agent_ids.length,0);assert.equal(ad.text_review_status,'reviewed');assert.ok(!ad.ad_text.includes('Sponsored'));});
test('unavailable acquisition is saved as a coverage gap without false ad assessments',async()=>{const m=load({found:{status:'unavailable',reason:'login_required',cards:[]}});const result=await m.runOfficeSocial(database(),'owner',setup);assert.equal(result.evidence.ads.length,0);assert.equal(result.evidence.acquisition_status,'unavailable');assert.match(result.evidence.coverage_gaps.join(' '),/not a clean compliance result/);});
test('one social capture per batch, with stale-running recovery',async()=>{const m=load();await m.runOfficeSocial(database({status:'complete',searched_at:'2026-09-23T19:10:00Z'}),'owner',setup,'2026-09-23T19:00:00Z');assert.equal(m.collected(),0);await m.runOfficeSocial(database({status:'running',searched_at:'2020-01-01T00:00:00Z'}),'owner',setup,'2019-01-01T00:00:00Z');assert.equal(m.collected(),1);});
