SET test.owner='11111111-1111-1111-1111-111111111111';
SET ROLE authenticated;
SELECT eyeonads_start_discovery_job(); SELECT eyeonads_start_discovery_job();
DO $$ BEGIN IF (SELECT count(*) FROM eyeonads_discovery_job_items)<>2 THEN RAISE EXCEPTION 'duplicate or completed item queued'; END IF; END $$;
SET test.owner='22222222-2222-2222-2222-222222222222';
DO $$ BEGIN IF (SELECT count(*) FROM eyeonads_discovery_job_items)<>0 THEN RAISE EXCEPTION 'owner leak'; END IF; END $$;
RESET ROLE;
DO $$ BEGIN IF has_function_privilege('authenticated','eyeonads_claim_discovery_job_item()','EXECUTE') OR has_function_privilege('anon','eyeonads_start_discovery_job()','EXECUTE') THEN RAISE EXCEPTION 'worker exposed'; END IF; END $$;
SET ROLE service_role;
CREATE TEMP TABLE claimed AS SELECT * FROM eyeonads_claim_discovery_job_item();
DO $$ BEGIN IF (SELECT count(*) FROM claimed)<>1 OR (SELECT count(*) FROM eyeonads_claim_discovery_job_item())<>0 THEN RAISE EXCEPTION 'parallel claim'; END IF; END $$;
SELECT eyeonads_finish_discovery_job_item(id,lease_token,false) FROM claimed;
TRUNCATE claimed; INSERT INTO claimed SELECT * FROM eyeonads_claim_discovery_job_item();
SELECT eyeonads_finish_discovery_job_item(id,lease_token,false) FROM claimed;
TRUNCATE claimed; INSERT INTO claimed SELECT * FROM eyeonads_claim_discovery_job_item();
SELECT eyeonads_finish_discovery_job_item(id,lease_token,false) FROM claimed;
DO $$ BEGIN IF (SELECT status FROM eyeonads_discovery_jobs)<>'failed' OR (SELECT count(*) FROM eyeonads_claim_discovery_job_item())<>0 THEN RAISE EXCEPTION 'three failures did not halt'; END IF; END $$;
SET ROLE authenticated; SET test.owner='11111111-1111-1111-1111-111111111111';
SELECT eyeonads_control_discovery_job('resume'); SELECT eyeonads_control_discovery_job('pause');
SET ROLE service_role;
DO $$ BEGIN IF (SELECT count(*) FROM eyeonads_claim_discovery_job_item())<>0 THEN RAISE EXCEPTION 'paused claim'; END IF; END $$;
SET ROLE authenticated; SELECT eyeonads_control_discovery_job('resume'); SET ROLE service_role;
TRUNCATE claimed; INSERT INTO claimed SELECT * FROM eyeonads_claim_discovery_job_item();
UPDATE eyeonads_discovery_job_items SET lease_until=now()-interval '1 second' WHERE id IN(SELECT id FROM claimed);
CREATE TEMP TABLE replacement AS SELECT * FROM eyeonads_claim_discovery_job_item();
DO $$ BEGIN IF (SELECT count(*) FROM replacement)<>1 THEN RAISE EXCEPTION 'abandoned item not reclaimed'; END IF; IF (SELECT eyeonads_finish_discovery_job_item(id,lease_token,true) FROM claimed) THEN RAISE EXCEPTION 'stale lease accepted'; END IF; END $$;
SELECT eyeonads_finish_discovery_job_item(id,lease_token,true) FROM replacement;
TRUNCATE claimed; INSERT INTO claimed SELECT * FROM eyeonads_claim_discovery_job_item();
SELECT eyeonads_finish_discovery_job_item(id,lease_token,true) FROM claimed;
DO $$ BEGIN IF (SELECT status FROM eyeonads_discovery_jobs)<>'complete' THEN RAISE EXCEPTION 'not completed'; END IF; END $$;
SELECT 'ALL QUEUE ASSERTIONS PASSED' AS result;
